### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by davwheat** [morefigs/timed-count#1]
Out of interest, are there any features from Python 3.10/3.11 used in this module at the moment? I hoped to use PyPy and this module together, but PyPy is still on Python 3.9 while this module is set to 3.10+ only support.

**Comment by morefigs** [comment]
I can't see any obvious reason it wouldn't work with Python 3.7+, so it should be fine.

I'll leave this issue open and properly support older versions of Python.

**Comment by morefigs** [comment]
timed-count v1.1.1 now supports Python v3.7+, thanks for the heads up.

**Comment by davwheat** [comment]
Thanks for the quick resolution! :)
